<?php


namespace Tests\Feature\Commands;

use Tests\TestCase;

/**
 *@coversDefaultClass \App\Commands\SetupCommand
 */
class SetupCommandTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @covers ::handle
     */
    public function test_setup_redgram_command()
    {
        $this->markTestIncomplete();
    }
}
